config/routes.rb
Crm::Application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  opinio_model
  
  get "/lookup" => 'api#lookup'
  get "/api/tags" => 'api#tags'
  get "audits/index"
  
  resources :image_guesses
  resources :reminders
  resources :opportunities
  
  resources :contacts do
    member do 
      get :vcard
    end
    resources :audits
    resources :opportunities
    resources :image_guesses
    resources :reminders
    opinio
  end
  
  resources :organisations do
    member do
      get :contacts_list
    end
    resources :audits
    resources :opportunities
    resources :image_guesses
    resources :reminders
    opinio
    resources :contacts do
      opinio
    end
  end

  root 'home#index'
  

  

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  
  audited
  attr_protected
  opinio_subjectum
  acts_as_taggable
  
  belongs_to :industry
  belongs_to :org_type
  has_one :image_guess, -> { where('accepted <> -1') }, :as => :guessable
  has_many :contacts
  has_many :reminder
  has_many :opportunities, -> { order('(amount * probability) DESC') }
  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "75x75>" }, :default_url => "/images/:style/missing_logo.png"  

  attr_accessor :delete_image, :reset_image_guess
  before_validation { image.clear if delete_image == '1'; ImageGuess.reset( self ) }
   
  validates_presence_of :name, :org_type_id
   
  #
  #
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
  #
  #
  def all_comments
    Comment.where( ["(commentable_type = 'Organisation' and commentable_id = ?) or (commentable_type = 'Contact' and commentable_id in (?))",
      self.id, self.contacts.map(&:id)] ).order( :created_at => :desc ) 
  end
  
  #
  #
  def current_contacts
    self.contacts.where( ex_organisation: false )
  end
  
  #
  #
  def image_search_urls
    term = "logo \"#{(not self.official_name.blank?) ? self.official_name : self.name}\""
    ["http://ajax.googleapis.com/ajax/services/search/images?imgsz=medium&v=1.0&q=#{CGI.escape(term)}"]
  end
      
end

app/controllers/organisations_controller.rb
class OrganisationsController < ResourcesController
  
  #
  #
  def index
    @organisations = Organisation.all
    
    @organisations.where! ['organisations.website like ?', "%#{params[:website]}%"] unless params[:website].blank?
    @organisations.where! ['organisations.city like ?', "%#{params[:city]}%"] unless params[:city].blank?
    @organisations.where! ['organisations.name like ? or organisations.official_name like ?', "%#{params[:name]}%", "%#{params[:name]}%"] unless params[:name].blank?
    @organisations.where! ['org_type_id = ?', params[:org_type]] unless params[:org_type].blank?
    @organisations.where! ['id = ?', params[:id]] unless params[:id].blank?
    
    @organisations = @organisations.order(:name).page params[:page]
  end
  
  #
  #
  def contacts_list
    resource
  end

  protected
  
end

app/helpers/organisation_helper.rb
module OrganisationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_contact.html.erb
<strong><%= link_to contact.name, [contact.organisation, contact] %></strong>
<% unless contact.department.blank? %>
	<span class="text-muted"> - <%= contact.department %></span> 
<% end %>
<% unless contact.position.blank? %>
	<span class="text-muted"> - <%= contact.position %></span> 
<% end %>
<br/>
<%= contact.phone_work %>
<%= contact.phone_mobile %>

app/views/organisations/_contacts.html.erb
<div class="panel organisation-contacts">
  <div class="panel-heading">Contacts</div>
	<ul class="list-group">
		<% if params[:show] == 'all' or (count = @organisation.current_contacts.count) <= 5 %>
			<% @organisation.current_contacts.order( [:firstname, :lastname] ).each do |contact| %>
				<li class="list-group-item organisation-contact">
					<%= render partial: 'contact', object: contact %>
				</li>
			<% end %>
		<% end %>

		<% if count > 5  %>
			<li class="list-group-item">
				<%= @organisation.current_contacts.order( [:firstname, :lastname] ).map{|c| 
					link_to("#{c.firstname} #{c.lastname}", c ) }.join(', ').html_safe %>				
			</li>
		<% end %>
		
		<li class="list-group-item show-organisation-contacts">		
			<%= link_to "New Contact", new_organisation_contact_path( @organisation ) %>
		
			<%= content_tag :span do %>
				| <%= link_to "Show all Contacts", organisation_contacts_path( @organisation ) %>
			<% end if count > 5 %>
		</li>			
		
	</ul>
</div>				

app/views/organisations/_form.html.erb
<%= semantic_form_for @organisation, :html => { :multipart => true } do |f| %>

	<div class="row">
		<div class="col-lg-12">
			<%= f.actions class: 'pull-right' do %>
				<%= f.action :submit %>
				<%= f.action :cancel, url: polymorphic_path( f.object ), label: "Cancel" %>
			<% end %>
		</div>	
	</div>

	<div class="row">

		<div class="col-lg-6">
			<%= f.inputs do %>				
				<li class="string input optional stringish" id="organisation_active_input">
					<label class=" label" for="organisation_active">Active</label>
					<%= f.check_box :active %>
				</li>
				<%= f.input :name %>
				<%= f.input :official_name %>
				<%= f.input :phone %>
				<%= f.input :fax %>
				<%= f.input :email %>
				<%= f.input :website %>
				<%= f.input :facebook %>
		
				<%= f.input :tag_list, input_html: {class: 'tags' } %>
			<% end %>
				
			<hr/>
			
			<%= f.inputs do %>	
				<%= f.input :description, input_html: { rows: 5 } %>
			<% end %>
				
		</div>

		<div class="col-lg-6" style="padding-top:40px;">
			<%= f.inputs do %>

				<%= f.input :address1 %>
				<%= f.input :address2 %>
				<%= f.input :zipcode %>
				<%= f.input :city %>
				<%= f.input :country, as: :select, collection: country_select_options %>

				<hr/>
				
				<%= f.input :org_type %>
				<%= f.input :industry %>			
				
				<hr/>
				<li class="formtastic-info">
					<%= image_tag @organisation.image.url(:thumb) %>
				</li>
				<%= f.input :image %>
				<li class="input optional">
					<label class="label">Delete Image and start guesses again</label>
					<%= f.check_box(:delete_image) %>
				</li>
				
			<% end %>
			
		</div>

	</div>
		
<% end %>

app/views/organisations/_opportunities.html.erb
<div class="panel">
  <div class="panel-heading">Opportunities</div>
	<ul class="list-group">
		<% count = @organisation.opportunities.open.count %>
		<%= render partial: 'opportunity', collection: @organisation.opportunities.open.limit(3) %>
		<%= content_tag :li, class: 'list-group-item' do %>
			<%= content_tag :span, count, class: 'badge' %>
		  <%= link_to "All opportunities", organisation_opportunities_path( @organisation ) %>
		<% end if count > 3 %>
		<%= content_tag :li, class: 'list-group-item' do %>
			<%= link_to "New", new_organisation_opportunity_path(@organisation) %>
		<% end %>
	</ul>
</div>

app/views/organisations/_opportunity.html.erb
<li class="list-group-item">
	<p>
		<%= link_to opportunity.name, [opportunity.organisation, opportunity] %>
	</p>
	<p>
		<%= content_tag :span, opportunity.opportunity_status.name, 
					class: "label", style: "background-color: ##{opportunity.opportunity_status.color}" %>
		<%= content_tag :span, opportunity.opportunity_typ.name, 
					class: "label", style: "background-color: ##{opportunity.opportunity_typ.color}" %>
		<%= content_tag :span, opportunity.lead_source.name, 
					class: "label", style: "background-color: ##{opportunity.lead_source.color}" %>
	</p>
	<p>
		<%= render partial: 'opportunities/expected', object: opportunity.expected %>
	</p>
</li>

app/views/organisations/_organisation.html.erb
<div class="panel <%= 'ex-organisation' if shade %>">
	<div class="panel-heading">		
		<strong><%= link_to organisation.name, organisation %></strong>
		<%= content_tag :span, "ex organisation", class: "label label-warning" if shade %>
	</div>
	<div class="contact-logo text-center">
		<%= render partial: 'image_guesses/image', locals: { holder: organisation, guess: true } %>
	</div>
  <ul class="list-group">
		<%= content_tag :li, class: 'list-group-item' do %>
			<%= content_tag :span, organisation.org_type.name, class: "label label-default" if organisation.org_type %>
			<%= content_tag :span, organisation.industry.name, class: "label label-default" if organisation.industry %>	
			<% organisation.tags.each do |tag| %>
				<span class="label label-info"><%= tag %></span>
			<% end %>			
		<% end if organisation.org_type  or organisation.industry or not organisation.tags.empty? %>
		
		<%= content_tag :li, class: 'list-group-item' do %>
			<strong><%= organisation.official_name ? organisation.official_name : organisation.name %></strong>
			<%#= render partial: 'shared/address', object: organisation %>
		<% end if false %>
		<%= content_tag :li, class: 'list-group-item' do %>
			<%= organisation.description %>
		<% end unless organisation.description.blank? %>
	</ul>
</div>

app/views/organisations/contacts_list.html.erb
<%= render partial: 'contacts' %>

app/views/organisations/edit.html.erb
<%= content_tag :h3, @organisation.org_type.name, class: "text-muted" if @organisation.org_type %>
<h1><%= @organisation.name %></h1>
<hr/>

<%= render partial: 'form'  %>

app/views/organisations/index.html.erb
<div class="content-actions">
	<%= link_to "New", new_organisation_path, class: "btn btn-small btn-lg" %>
</div>

<div class="page-header">	
	<h1>Organisations</h1>
</div>

<%= form_tag organisations_path, class: 'search-form', method: 'get' do %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>City</th>
				<th>Type</th>
				<th>Website</th>
			</tr>
			<tr>
				<th><%= text_field_tag :id, params[:id] %></th>
				<th><%= text_field_tag :name, params[:name] %></th>
				<th><%= text_field_tag :city, params[:city] %></th>
				<th><%= select_tag :org_type, 
									options_for_select( OrgType.all( order: :name ).map{|ot| [ot.name, ot.id]}, 
										params[:org_type] ), 
									include_blank: true %></th>
				<th><%= text_field_tag :website, params[:website] %></th>
				<th><%= submit_tag "Filter" %></th>				
			</tr>
		</thead>
		<tbody>
			<% @organisations.each do |organisation| %>
			<tr>
				<td>
					<%= link_to organisation.id, organisation %>
				</td>
				<td>
					<%= link_to organisation.name, organisation %>
				</td>
				<td>
					<%= organisation.city %>
				</td>
				<td>
					<%= organisation.org_type.name if organisation.org_type %>
				</td>
				<td>
					<%= organisation.website %>
				</td>
				<td>					
				</td>
			</tr>
			<% end %>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="6">
					<%= paginate @organisations %>
				</td>
			</tr>
		</tfoot>
	</table>
	
<% end %>	
	

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render 'form' %>

app/views/organisations/show.html.erb
<div class="content-actions">
	<%= link_to "Edit", edit_organisation_path(@organisation), class: "btn btn-small btn-lg" %>
</div>

<%= content_tag :h3, @organisation.org_type.name, class: "text-muted" if @organisation.org_type %>
<h1><%= @organisation.name %></h1>
<hr/>

<div class="row">
	
	<div class="col-lg-4">
		<div class="panel">
			<div class="panel-heading">
				<strong><%= @organisation.official_name ? @organisation.official_name : @organisation.name %></strong>
			</div>
			<p>				
				<%= render partial: 'shared/address', object: @organisation %>
			</p>
		  <ul class="list-group">
				
				<%= content_tag :li, class: "list-group-item" do %>
					<label>Phone:</label>
					<%= @organisation.phone %>
				<% end unless @organisation.phone.blank? %>

				<%= content_tag :li, class: "list-group-item" do %>
					<label>Fax:</label>
					<%= @organisation.fax %>
				<% end unless @organisation.fax.blank? %>

				<%= content_tag :li, class: "list-group-item" do %>
					<label>Email:</label>
					<%= @organisation.email %>
				<% end unless @organisation.email.blank? %>

				<%= content_tag :li, class: "list-group-item" do %>
					<label>Website:</label>
					<%= link_to( @organisation.website, @organisation.website, target: '_blank' ) %>
				<% end unless @organisation.website.blank? %>

		  </ul>
		</div>				
	</div>
	
	<div class="col-lg-5" id="organisation-contacts">
		<%= render partial: 'contacts' %>
	</div>
	
	<div class="col-lg-3">
		<div class="panel">
			<div class="organisation-logo">
				<%= render partial: 'image_guesses/image', locals: { holder: @organisation, guess: true } %>
			</div>
		  <ul class="list-group">
				<%= content_tag :li, class: 'list-group-item' do %>
					<%= content_tag :span, @organisation.industry.name, class: "label label-default" %>
					<% @organisation.tags.each do |tag| %>
						<span class="label label-info"><%= tag %></span>
					<% end %>					
				<% end if @organisation.industry %>
				<%= content_tag :li, class: 'list-group-item' do %>
					<%= @organisation.description %>
				<% end unless @organisation.description.blank? %>
			</ul>
		</div>
	</div>

</div>
<hr/>
	
<div class="row">

	<div class="col-lg-4">
		<div class="panel">
		  <div class="panel-heading">Notes</div>
			<%= render partial: 'opinio/comments/form', locals: { commentable: @organisation, comment: Comment.new } %>			
			<%= render partial: 'opinio/comments/comments', object: @organisation.all_comments %>
		</div>				
	</div>

	<div class="col-lg-4">
		<div class="panel">
		  <div class="panel-heading">History</div>
			<%= render partial: 'audits/audits', object: @organisation.audits %>
		</div>
	</div>

	<div class="col-lg-4">
		<%= render partial: 'opportunities' %>
	</div>

</div>