config/routes.rb
Crm::Application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  opinio_model
  
  get "/lookup" => 'api#lookup'
  get "/api/tags" => 'api#tags'
  get "audits/index"
  
  resources :image_guesses
  resources :reminders
  resources :opportunities
  
  resources :contacts do
    member do 
      get :vcard
    end
    resources :audits
    resources :opportunities
    resources :image_guesses
    resources :reminders
    opinio
  end
  
  resources :organisations do
    member do
      get :contacts_list
    end
    resources :audits
    resources :opportunities
    resources :image_guesses
    resources :reminders
    opinio
    resources :contacts do
      opinio
    end
  end

  root 'home#index'
  

  

end

app/controllers/image_guesses_controller.rb
require 'timeout'
class ImageGuessesController < ResourcesController
  
  #
  #
  def new
    @parent = (params[:parent_type].constantize).find params[:parent_id]

    begin
      status = Timeout::timeout(10) {
        ImageGuess.get_image( @parent )    
        render action: 'show'      
      }      
    rescue Exception => e
      # siltently do nothing 
      render nothing: true
    end     
  end
  
  #
  #
  def update
    @parent = resource.guessable
    
    if params[:accepted] == 'true'
      resource.update_attribute( :accepted, 1 )
      @parent.image = resource.image
      @parent.save!
    else
      resource.accepted = -1
      resource.image = nil
      resource.save!
      ImageGuess.get_image @parent
    end
    
    render action: 'show'
  end
end

app/helpers/image_guesses_helper.rb
module ImageGuessesHelper
end

app/views/image_guesses/_image.html.erb
<div id="<%= holder.css_id %>">
	<% if holder.image? %>

		<%= image_tag holder.image.url(:medium) %>

	<% elsif holder.image_guess and holder.image_guess.image? %>

		<%= image_tag holder.image_guess.image.url(:medium) %>

		<% if holder.image_guess.accepted.nil? or holder.image_guess.accepted == 0 %>
			<p class="text-muted">
				<small>
					This image is a guess. Is it 
				 	<%= link_to "correct", 
								image_guess_path( holder.image_guess, accepted: true ), 
								method: :patch,
								remote: true %> | 
					<%= link_to "not correct?", 
								image_guess_path( holder.image_guess, accepted: false ), 
								method: :patch,
								remote: true %> 
				</small>
			</p>
		<% end %>

	<% else %>

		<%= image_tag holder.image.url(:medium) %>
		
		<% if guess %>
			<script type="text/javascript" charset="utf-8">
				$.get("<%= new_image_guess_path( :parent_type => holder.class.to_s, :parent_id => holder.id.to_i ).html_safe %>");
			</script>
		<% end %>
	<% end %>
</div>

app/views/image_guesses/show.js.erb
$('#<%= @parent.css_id %>').html( '<%= j render partial: "image_guesses/image", locals: {holder: @parent, guess: false } %>' );