config/routes.rb
Crm::Application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  opinio_model
  
  get "/lookup" => 'api#lookup'
  get "/api/tags" => 'api#tags'
  get "audits/index"
  
  resources :image_guesses
  resources :reminders
  resources :opportunities
  
  resources :contacts do
    member do 
      get :vcard
    end
    resources :audits
    resources :opportunities
    resources :image_guesses
    resources :reminders
    opinio
  end
  
  resources :organisations do
    member do
      get :contacts_list
    end
    resources :audits
    resources :opportunities
    resources :image_guesses
    resources :reminders
    opinio
    resources :contacts do
      opinio
    end
  end

  root 'home#index'
  

  

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  
  audited
  attr_protected
  opinio_subjectum
  acts_as_taggable
  
  belongs_to :organisation
  belongs_to :contact
  belongs_to :user
  belongs_to :opportunity_status
  belongs_to :opportunity_typ
  belongs_to :lead_source
  has_many :reminders, as: :reminderable
  
  scope :open, -> { includes(:opportunity_status).where( 'opportunity_statuses.closed' => false ) }
  
  validates_presence_of :organisation_id, :opportunity_status_id, :opportunity_typ_id, :lead_source_id, :name, :amount, :probability, :user_id
  validates_numericality_of :amount, :probability, only_integer: true, greater_than: 0
  
  #
  #
  def self.max_open
    Opportunity.includes(:opportunity_status).where( 'opportunity_statuses.closed = 0' ).maximum('amount * (probability/100.0)')
  end
  
  #
  #
  def self.open_sum
    self.open.sum(&:expected)
  end
  
  #
  #
  def expected
    amount * (probability / 100.0)
  end
  
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ResourcesController
  
  belongs_to :organisation, optional: true
  
  before_action :redirect_with_parent, only: :show
  
  #
  #
  def index
    
    unless params[:id].blank?
      opportunitiy = Opportunity.find params[:id] 
      redirect_to [opportunitiy.organisation, opportunitiy]
    end
    
    @info = {}
    
    opportunities = end_of_association_chain.includes([:opportunity_status, :opportunity_typ, :organisation] )
    
    opportunities.where! ['opportunities.name like ?', "%#{params[:name]}%"] unless params[:name].blank?
    opportunities.where! ['organisations.name like ?', "%#{params[:organisation]}%"] unless params[:organisation].blank?    
    opportunities.where! ['opportunities.user_id = ?', params[:assigned]] unless params[:assigned].blank?    
    
    params[:status] ||= '_open'
    
    closed = false
    
    case params[:status]
      when "_open"
        opportunities.where!( 'opportunity_statuses.closed = 0' )
      when "_closed"
        opportunities.where!( 'opportunity_statuses.closed = 1' )
        closed = true        
      else
        opportunities.where!( ['opportunity_status_id = ?', params[:status]] )
        closed = OpportunityStatus.find( params[:status] ).closed?        
    end    
      
    @info[:max] = closed ? opportunities.maximum('amount * (probability/100.0)') : Opportunity.max_open unless @info[:max]
    
    set_info( opportunities ) unless closed
    
    @opportunities = opportunities.order('(amount * probability) DESC').page params[:page]    
  
  end
  
  
  #
  #
  def update
    update! { [resource.organisation, resource]}
  end
  
  protected
  
  #
  #
  def set_info( opportunities )
    
    return if (count = opportunities.size) <= 1

    @info[:count] = count
    
    return if @info[:count] <= 1
    
    @info[:open] = opportunities.open.sum(&:expected)
    @info[:status] = {}
    opportunities.group_by(&:opportunity_status_id).each do |key, opportunities| 
      status = OpportunityStatus.find key
      @info[:status][status] = [opportunities.sum(&:expected)]
      @info[:status][status] << @info[:status][status].first / @info[:open] 
    end

    @info[:lead_source] = {}
    opportunities.group_by(&:lead_source_id).each do |key, opportunities| 
      lead_source = LeadSource.find key
      @info[:lead_source][lead_source] = [opportunities.sum(&:expected)]
      @info[:lead_source][lead_source] << @info[:lead_source][lead_source].first / @info[:open] 
    end
    
    @info[:opportunity_typ] = {}
    opportunities.group_by(&:opportunity_typ_id).each do |key, opportunities| 
      typ = OpportunityTyp.find key
      @info[:opportunity_typ][typ] = [opportunities.sum(&:expected)]
      @info[:opportunity_typ][typ] << @info[:opportunity_typ][typ].first / @info[:open] 
    end
    
  end
  
  #
  #
  def redirect_with_parent
    unless parent
      redirect_to [resource.organisation, resource]
    end
  end
  
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
    
end

app/views/opportunities/_expected.html.erb
<% percent = expected / Opportunity.max_open * 100.0 %>
<div class="progress">
	<%= content_tag :div, class: "progress-bar", style: "width:#{percent}%" do %>
			<span class="pull-left" style="margin-left:10px;"><%= percent >= 25 ? nf(expected) : space %></span>
	<% end %>
	<% if percent < 25 %>
		<span style="margin-left:10px;"><%= nf expected %> €</span>
	<% end %>
</div>

app/views/opportunities/_form.html.erb
<% @opportunity.user ||= current_user %>

<%= semantic_form_for [@organisation, @opportunity], :html => { :multipart => true } do |f| %>

	<div class="row">
		<div class="col-lg-12">
			<%= f.actions class: 'pull-right' do %>
				<%= f.action :submit %>
				<%= f.action :cancel, url: polymorphic_path( f.object ), label: "Cancel" %>
			<% end %>
		</div>	
	</div>

	<div class="row">

		<div class="col-lg-6">
			<%= f.inputs do %>	
				<%= f.input :opportunity_status %>
				<%= f.input :opportunity_typ %>
	      <%= f.input :name %>
				<%= f.input :amount, as: :string, input_html: { maxlength: 9 } %>
				<%= f.input :probability, as: :select, collection: (5..95).step(5).map{|i| ["#{i}%", i]} %>
			<% end %>
			
			<hr/>
						
			<%= f.inputs do %>	
				<%= f.input :description, input_html: { rows: 5 } %>
				<%= f.input :tag_list, input_html: {class: 'tags'} %>				
			<% end %>
		</div>

		<div class="col-lg-6" style="padding-top:40px;">
			
			<%= f.inputs do %>
				<%= f.input :lead_source %>
				<%= f.input :organisation, collection: Organisation.order(:name), 
										input_html: { :onchange => "$.get('/organisations/' + $(this).val() + '/contacts.js' )" } %>
				<%= f.input :contact, collection:( @opportunity.organisation ? @opportunity.organisation.contacts.order(:firstname ) : [] ),
					 					input_html: { id: 'contacts' } %>
			<% end %>
			
			<hr/>

			<%= f.inputs do %>	
				<%= f.input :user, collection: User.assignable.order(:firstname) %>
				<%= f.input :next_date, as: :string, input_html: { class: 'date-picker' } %>
				<%= f.input :next_steps, input_html: { rows: 3 } %>
			<% end %>
		</div>

	</div>
		
<% end %>

app/views/opportunities/_reminder.html.erb
<div class="panel">
	<div class="panel-heading">
		Reminder
	</div>
	<ul class="list-group">
		<% @opportunity.reminders.each do |reminder| %>
			<%= content_tag :li, class: 'list-group-item' do %>
				<%= lna reminder.date %> 
				<span class="label label-info"><%= reminder.typ %></span>
				<%= reminder.note %>
			<% end %>
		<% end %>
		<li class="list-group-item text-right">
			<%= link_to "New reminder", polymorphic_path([@contact, Reminder.new], action: :new ), onclick: "alert('Not implemented'); return false;" %>
		</li>
	</ul>
</div>		

app/views/opportunities/_summary.html.erb
<div class="well">

	<h4 class="text-right">Open: <%= nf @info[:open] %> €</h4>

	<h5 class="text-muted">Per sales stage</h5>
	<div class="progress">
		<% @info[:status].each do |status, value| %>
			<% next if value[1] < 0.1 %>
			<%= content_tag :div, class: "progress-bar", style: "width: #{value[1]*100}%;background-color: ##{status.color}!important;" do %>
				<span class="sr-only"><%= status.name %> (€ <%= nf value[0]%>)</span>
			<% end %>
		<% end %>
	</div>

	<h5 class="text-muted">Per business type</h5>
	<div class="progress">
		<% @info[:opportunity_typ].each do |status, value| %>
			<% next if value[1] < 0.1 %>
			<%= content_tag :div, class: "progress-bar", style: "width: #{value[1]*100}%;background-color: ##{status.color}!important;" do %>
				<span class="sr-only"><%= status.name %> (€ <%= nf value[0]%>)</span>
			<% end %>
		<% end %>
	</div>

	<h5 class="text-muted">Per lead source</h5>
	<div class="progress">

		<% @info[:lead_source].each do |status, value| %>
			<% next if value[1] < 0.1 %>			
			<%= content_tag :div, class: "progress-bar", style: "width: #{value[1]*100}%;background-color: ##{status.color}!important;" do %>
				<span class="sr-only"><%= status.name %> (€ <%= nf value[0]%>)</span>
			<% end %>
		<% end %>
	</div>
	
	<div class="text-right"><small class="text-muted">Rest to 100%: other &lt; 10%</small></div>
	
</div>

<hr/>

app/views/opportunities/_table.html.erb
<%= form_tag opportunities_path, class: 'search-form', method: 'get' do %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th width="80">ID</th>
				<th>Name</th>
				<% unless @organisation %><th>Organisation</th><% end %>
				<th>Status</th>
				<th>Assigned</th>
				<th>Type</th>
				<th>Amount</th>
				<th>Probality</th>
				<th width="20%">Expected</th>
			</tr>
			<tr>
				<th><%= text_field_tag :id, params[:id], class: "form-control" %></th>
				<th><%= text_field_tag :name, params[:name], class: "form-control" %></th>
				<% unless @organisation %><th><%= text_field_tag :organisation, params[:organisation], class: "form-control" %></th><% end %>
				<th>
					<%= select_tag :status, options_for_select( opportunity_status_options, params[:status] ), class: "form-control auto-submit" %>
				</th>
				<th>
					<%= select_tag :assigned, 
								options_for_select( [nil] + User.assignable.map{|u| [u.name, u.id]}, params[:assigned] ), 
								class: "form-control auto-submit" %>
				</th>
				<th></th>
				<th></th>
				<th></th>
				<th class="text-right"><%= submit_tag "Filter", class: "form-control pull-right", style: "width: 80px;" %></th>
			</tr>
		</thead>
		<tbody>
			<% @opportunities.each do |opportunity| %>
			<tr>
				<td>
					<%= link_to opportunity.id, [opportunity.organisation, opportunity] %>
				</td>
				<td>
					<%= link_to opportunity.name, [opportunity.organisation, opportunity] %>
				</td>
				<% unless @organisation %>
					<td>
						<%= link_to opportunity.organisation.name, opportunity.organisation %>
					</td>
				<% end %>
				<td>
					<%= opportunity.opportunity_status.name %>
				</td>
				<td>
					<%= opportunity.user.name if opportunity.user %>
				</td>
				<td>
					<%= opportunity.opportunity_typ.name %>
				</td>
				<td>
					<%= nf opportunity.amount %>
				</td>
				<td>
					<%= nf opportunity.probability %>%
				</td>
				<td>
					<% expected = nf( opportunity.expected, 0 ) %>
					<% percent = opportunity.expected/@info[:max] * 100.0 %>					
					<%= content_tag :div, class: "progress-bar", style: "width:#{percent}%" do %>
							<span class="pull-left" style="margin-left:10px;"><%= percent >= 25 ? nf(opportunity.expected) : "&nbsp;".html_safe %></span>
					<% end %>
					<% if percent < 25 %>
						<span style="margin-left:10px;"><%= nf opportunity.expected %></span>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="6">
					<%= paginate @opportunities %>
				</td>
			</tr>
		</tfoot>
	</table>
	
<% end %>	

app/views/opportunities/edit.html.erb
<div class="page-header">
	<%= content_tag :h3, link_to( @organisation.name, @organisation ) %>
	<%= content_tag :h1, @opportunity.name %>
</div>

<%= render partial: 'form'  %>

app/views/opportunities/index.html.erb
<div class="content-actions">
	<%= link_to "New", new_opportunity_path, class: "btn btn-small btn-lg" %>
</div>

<div class="page-header">	
	<%= content_tag :h3, link_to( @organisation.name, @organisation ) if @organisation %>
	<h1>Opportunities</h1>
</div>

<%= render partial: 'summary' if @info[:count] %>

<%= render partial: 'table' %>

	

app/views/opportunities/new.html.erb
<h1>New opportunity</h1>

<%= render 'form' %>

app/views/opportunities/show.html.erb
<div class="content-actions">
	<%= link_to "Edit", edit_organisation_opportunity_path(@organisation, @opportunity), class: "btn btn-small btn-lg" %>
</div>

<div class="page-header">
	<%= content_tag :h3, link_to( @organisation.name, @organisation ) %>
	<%= content_tag :h1, "Opportunity: #{@opportunity.name}"%>
	<%= content_tag :div do %>
		<% @opportunity.tags.each do |tag| %>
				<div class="tag">
					<%= content_tag :span, tag, class: 'badge' %>
				</div>
		<% end %>		
		<div style="clear:both;"></div>
	<% end %>
</div>

<div class="row">
	
	<div class="col-lg-3">
		<ul class="list-group">
			<%= content_tag :li, class: "list-group-item" do %>
				<%= content_tag :span, "#{nf(@opportunity.amount)} €", class: 'badge'%>
				<label>Amount:</label>
			<% end %>
			<%= content_tag :li, class: "list-group-item" do %>
				<%= content_tag :span, "#{nf(@opportunity.probability)} %", class: 'badge'%>
				<label>Probability:</label>
			<% end %>
			<%= content_tag :li, class: "list-group-item" do %>
				<label>Expected:</label>
				<div style="margin-right:-15px;">
					<%= render partial: 'opportunities/expected', object: @opportunity.expected %>				
				</div>
			<% end %>
		</ul>
	</div>
	
	<div class="col-lg-3">
		<ul class="list-group">
			<%= content_tag :li, class: "list-group-item" do %>
				<%= content_tag :span, space(5), class: 'badge', style: "background-color: ##{@opportunity.opportunity_status.color}" %>
				<label>Status:</label>
				<%= @opportunity.opportunity_status.name %>
			<% end %>
			<%= content_tag :li, class: "list-group-item" do %>
				<%= content_tag :span, space(5), class: 'badge', style: "background-color: ##{@opportunity.opportunity_typ.color}" %>
				<label>Type:</label>
				<%= @opportunity.opportunity_typ.name %>
			<% end %>
			<%= content_tag :li, class: "list-group-item" do %>
				<%= content_tag :span, space(5), class: 'badge', style: "background-color: ##{@opportunity.lead_source.color}" %>
				<label>Lead Source:</label>
				<%= @opportunity.lead_source.name %>
			<% end %>
			<%= content_tag :li, class: "list-group-item" do %>
				<label>Assigned:</label>
				<%= @opportunity.user.name %>
			<% end if @opportunity.user %>
			<%= content_tag :li, @opportunity.description, class: "list-group-item" if @opportunity.description %>
		</ul>
	</div>
	
	<div class="col-lg-3">
		<%= link_to @organisation do %>
			<%= render partial: 'organisations/organisation', object: @organisation, locals: { shade: false } %>
			<%= content_tag :div, class: 'panel' do %>
				<div class="panel-heading">		
					<strong><%= link_to @opportunity.contact.name, @opportunity.contact %></strong>					
				</div>			
				<ul class="list-group">
					<%= list_group_item( @opportunity.contact.department , "Department:" ) unless @opportunity.contact.department.blank? %>
					<%= list_group_item( @opportunity.contact.position , "Position:" ) unless @opportunity.contact.position.blank? %>
					<%= list_group_item @opportunity.contact.phone_work, "Phone:" %>
					<%= list_group_item @opportunity.contact.phone_mobile, "Mobile:" %>
				</ul>
			<% end if @opportunity.contact %>
		<% end %>
	</div>
	
	<div class="col-lg-3">
		<%= render partial: 'reminder' %>
	</div>
	
</div><!-- row -->